<?php
// -------------------------------------------------------------------
// This file was automatically generated by the LangBuilder.php script
// Date of creation: 2011/06/10 17:14:40
// -------------------------------------------------------------------
global $lang;


// Output for class or file: InvisibleSpamProtectionField
$lang['en_US']['InvisibleSpamProtectionField']['LEAVEEMPTY'] = 
	'If you see this field, please leave empty. It\'s a automated spam trap.';
$lang['en_US']['InvisibleSpamProtectionField']['FIELDNOTEMPTY'] = 
	'Anti-spam field is not empty. Please leave field unchanged.';
