<?php
// -------------------------------------------------------------------
// This file was automatically generated by the LangBuilder.php script
// Date of creation: 2011/06/10 17:14:40
// -------------------------------------------------------------------
global $lang;


// Output for class or file: InvisibleSpamProtectionField
$lang['en_US']['InvisibleSpamProtectionField']['LEAVEEMPTY'] =
	'Als je dit veld ziet, laat het dan leeg. Dit is een anti spam valkuil.';
$lang['en_US']['InvisibleSpamProtectionField']['FIELDNOTEMPTY'] =
	'Anti-spam veld is niet leeg. Laat ongewijzigd om formulier te verzenden.';
